### PR TITLE
fixes #1723 - correcting wrong "current_job" static variable use

### LINKED ISSUE #1723: [battlemod] Job filters are not reloaded
Actual result: When using `bm reload` command, job filters are not reloaded.

Expected result: `bm reload` should reload the current job's filters.

### PR DESCRIPTION
**Pull request by mharrington622**

### CODE REVIEW

File: addons/battlemod/battlemod.lua [hunk 1]
```diff
@@ -143,6 +143,11 @@ function flip_block_cannot()
     block_cannot = not block_cannot
 end
 
+function reload()
```
Comment (z16) [inline addons/battlemod/battlemod.lua]: I would just inline that function while you fix the tabs :)

**Review by z16 — CHANGES_REQUESTED** [review]
